name: cabal
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  build:
    runs-on: ubuntu-latest
    needs: fourmolu
    strategy:
      matrix:
        cabal: ["latest"]
        ghc: ["8.10.7", "9.0.2", "9.2.8", "9.4.8", "9.6.6", "9.8.3"]
    env:
      CONFIG: "--enable-tests --enable-benchmarks --flags=build-the-readme"
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal update
      - run: cabal freeze $CONFIG
      - uses: actions/cache@v3.0.7
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal build all $CONFIG
      - run: cabal test tmp-proc:integration-test tmp-proc-zipkin tmp-proc-rabbitmq tmp-proc-redis tmp-proc-postgres $CONFIG
      - run: cabal sdist all
