name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: adetokunbo/create-file-action@master
      env:
        FILE_NAME: ".config/nix/nix.conf"
        FILE_DATA: "trusted-public-keys = [...] hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= [...]\nsubstituters = [...] https://hydra.iohk.io [...]"
    - run: nix-build
